spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

minio:
  url: http://${MINIO_HOST}:${MINIO_API_PORT}
  bucket-name: ${MINIO_BUCKET_NAME}
  root:
    user: ${MINIO_ROOT_USER}
    password: ${MINIO_ROOT_PASSWORD}

logging:
  level:
    root: INFO

springdoc:
  api-docs:
    enabled: true
    path: /api/v3/api-docs
  swagger-ui:
    enabled: true
    path: /api/swagger-ui.html
    config-url: /api/v3/api-docs/swagger-config
    url: /api/v3/api-docs